name: Docker Image CI on GCP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted
   

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       sudo docker build -t dockerpy .
       sudo docker run --name dockerpy_gcp dockerpy:latest
       sudo docker rm -f dockerpy_gcp
      
      #. --file Dockerfile --tag my-image-name:$(date +%s)
