name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted
   

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       docker build -t dockerpy .
       docker run --name dockerpy_container dockerpy:latest
       docker rm -f dockerpy_container
      
      #. --file Dockerfile --tag my-image-name:$(date +%s)
